### ISSUE TITLE
So few plugin details in README.

### ISSUE THREAD

**Issue by kostamax27** [mcsim415/WParkour#3]
How to setup parkour? Record a video tutorial on setting up parkour

**Comment by deveworld** [comment]
See [this](https://github.com/mcsim415/WParkour/blob/main/README.md).

**Comment by deveworld** [comment]
If you can't understand, let me know.

**Comment by BroCrows** [comment]
Yeah the readme needs a revamp kinda.
It doesnt tell me a lot about the plugin, like what are the features and stuff

**Comment by deveworld** [comment]
How about adding more details to the wiki?
