### ISSUE TITLE
can't make parkor

### ISSUE THREAD

**Issue by ErwanScraft** [mcsim415/WParkour#4]
![Screenshot_2021-08-09-09-26-01-980_com mojang minecraftpe](https://user-images.githubusercontent.com/72255518/128655096-5c6e0617-964b-4a38-9bb2-d29bc3a20664.jpg)

When I want to make a parking arrangement at the start of the break block, nothing happens

**Comment by deveworld** [comment]
The server didn't log anything?

**Comment by deveworld** [comment]
I can't reproduce the problem. Tell me more about how the problem happened.

**Comment by ErwanScraft** [comment]
> The server didn't log anything?

Yes, the server doesn't log anything

**Comment by ErwanScraft** [comment]
When I want to make parkour, I click on the starting point but when I confirm and try to destroy the block/setting the start location nothing happens

**Comment by deveworld** [comment]
On mobile, you have to press and hold to break the block. Didn't you happen to press it short?

**Comment by deveworld** [comment]
On Windows 10 edition, you need to left-click.

**Comment by deveworld** [comment]
If not, would you like to re-test only this plugin with the latest version of PocketMine-MP?

**Comment by ErwanScraft** [comment]
https://user-images.githubusercontent.com/72255518/128745883-a571ae2d-3344-465a-86ad-a6a7717e57d3.mp4

**Comment by ErwanScraft** [comment]
I'm using the Dev 52 version and still can't make parkour, when I destroy the block nothing happens.

**Comment by deveworld** [comment]
Sorry. I can't find out what is the matter. But I think it's more likely the fault comes from one of your plugins.
